# Generated by Django 4.0.4 on 2022-05-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassi',
            name='numero',
            field=models.CharField(help_text='Informe 16 caracteres', max_length=16, verbose_name='Chassi'),
        ),
    ]
